#include <Rcpp.h>
using namespace Rcpp;

// Coupled logistic-map lattice update.
//
// Noise is generated by the R wrapper and passed in explicitly. Keeping RNG
// ownership in R guarantees that the reference and C++ implementations consume
// exactly the same perturbations under a common seed.

// [[Rcpp::export]]
NumericMatrix cml_simulate_cpp_impl(
    int n,
    double r,
    double coupling,
    NumericVector x0,
    NumericMatrix noise) {
  const int lattice_size = x0.size();

  if (n < 1) stop("n must be positive");
  if (lattice_size < 3) stop("lattice_size must be at least 3");
  if (noise.nrow() != std::max(0, n - 1) ||
      noise.ncol() != lattice_size) {
    stop("noise has incompatible dimensions");
  }

  NumericMatrix out(n, lattice_size);
  for (int j = 0; j < lattice_size; ++j) {
    out(0, j) = x0[j];
  }

  if (n == 1) return out;

  std::vector<double> mapped(lattice_size);

  for (int t = 1; t < n; ++t) {
    for (int j = 0; j < lattice_size; ++j) {
      const double x = out(t - 1, j);
      mapped[j] = r * x * (1.0 - x);
    }

    for (int j = 0; j < lattice_size; ++j) {
      const int left = (j == 0) ? lattice_size - 1 : j - 1;
      const int right = (j == lattice_size - 1) ? 0 : j + 1;

      out(t, j) =
        (1.0 - coupling) * mapped[j] +
        0.5 * coupling * (mapped[left] + mapped[right]) +
        noise(t - 1, j);
    }
  }

  return out;
}
