// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_logistic_map_cpp
NumericVector simulate_logistic_map_cpp(int n, double r, double x0);
RcppExport SEXP _chaoticds_simulate_logistic_map_cpp(SEXP nSEXP, SEXP rSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_logistic_map_cpp(n, r, x0));
    return rcpp_result_gen;
END_RCPP
}
// threshold_exceedances_cpp
IntegerVector threshold_exceedances_cpp(NumericVector x, double threshold);
RcppExport SEXP _chaoticds_threshold_exceedances_cpp(SEXP xSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(threshold_exceedances_cpp(x, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cluster_sizes_cpp
IntegerVector cluster_sizes_cpp(IntegerVector exceedance_indices, int run_length);
RcppExport SEXP _chaoticds_cluster_sizes_cpp(SEXP exceedance_indicesSEXP, SEXP run_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type exceedance_indices(exceedance_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type run_length(run_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_sizes_cpp(exceedance_indices, run_length));
    return rcpp_result_gen;
END_RCPP
}
// extremal_index_runs_cpp
double extremal_index_runs_cpp(NumericVector x, double threshold, int run_length);
RcppExport SEXP _chaoticds_extremal_index_runs_cpp(SEXP xSEXP, SEXP thresholdSEXP, SEXP run_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type run_length(run_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(extremal_index_runs_cpp(x, threshold, run_length));
    return rcpp_result_gen;
END_RCPP
}
// block_maxima_cpp
NumericVector block_maxima_cpp(NumericVector x, int block_size);
RcppExport SEXP _chaoticds_block_maxima_cpp(SEXP xSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(block_maxima_cpp(x, block_size));
    return rcpp_result_gen;
END_RCPP
}
// quantile_cpp
double quantile_cpp(NumericVector x, double prob);
RcppExport SEXP _chaoticds_quantile_cpp(SEXP xSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_cpp(x, prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chaoticds_simulate_logistic_map_cpp", (DL_FUNC) &_chaoticds_simulate_logistic_map_cpp, 3},
    {"_chaoticds_threshold_exceedances_cpp", (DL_FUNC) &_chaoticds_threshold_exceedances_cpp, 2},
    {"_chaoticds_cluster_sizes_cpp", (DL_FUNC) &_chaoticds_cluster_sizes_cpp, 2},
    {"_chaoticds_extremal_index_runs_cpp", (DL_FUNC) &_chaoticds_extremal_index_runs_cpp, 3},
    {"_chaoticds_block_maxima_cpp", (DL_FUNC) &_chaoticds_block_maxima_cpp, 2},
    {"_chaoticds_quantile_cpp", (DL_FUNC) &_chaoticds_quantile_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_chaoticds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
