#' Estimate the Lyapunov exponent of a logistic map
#'
#' Computes a simple estimate of the largest Lyapunov exponent for a
#' sequence generated by the logistic map.
#'
#' @param x Numeric vector of observations from the logistic map.
#' @param r Optional numeric parameter of the map. If `NULL`, it is
#'   estimated from consecutive observations.
#'
#' @return Numeric value giving the estimated Lyapunov exponent.
#' @examples
#' data(logistic_ts)
#' estimate_lyapunov_exponent(logistic_ts[1:1000])
#' @export
estimate_lyapunov_exponent <- function(x, r = NULL) {
  if (!is.numeric(x) || length(x) <= 1) {
    stop("x must be a numeric vector of length > 1")
  }
  if (!is.null(r) && (!is.numeric(r) || length(r) != 1)) {
    stop("r must be a single numeric value")
  }
  if (is.null(r)) {
    x_prev <- head(x, -1)
    x_next <- tail(x, -1)
    r <- mean(x_next / (x_prev * (1 - x_prev)))
  }
  deriv <- r * (1 - 2 * head(x, -1))
  mean(log(abs(deriv)))
}
