#' Estimate the Lyapunov exponent of a logistic map
#'
#' Computes a simple estimate of the largest Lyapunov exponent for a
#' sequence generated by the logistic map.
#'
#' @param x Numeric vector of observations from the logistic map.
#' @param r Optional numeric parameter of the map. If `NULL`, it is
#'   estimated from consecutive observations.
#'
#' @return Numeric value giving the estimated Lyapunov exponent.
#' @examples
#' data(logistic_ts)
#' estimate_lyapunov_exponent(logistic_ts[1:1000])
#' @export
estimate_lyapunov_exponent <- function(x, r = NULL) {
  checkmate::assert_numeric(x, min.len = 2)
  checkmate::assert_number(r, null.ok = TRUE)
  if (is.null(r)) {
    x_prev <- head(x, -1)
    x_next <- tail(x, -1)
    r <- mean(x_next / (x_prev * (1 - x_prev)))
  }
  deriv <- r * (1 - 2 * head(x, -1))
  mean(log(abs(deriv)))
}
