# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Hénon map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the Hénon map for improved performance.
#'
#' @param n Number of iterations
#' @param a Parameter a
#' @param b Parameter b
#' @param x0 Initial x value
#' @param y0 Initial y value
#' @return DataFrame with x and y columns
#' @export
simulate_henon_map_cpp <- function(n, a = 1.4, b = 0.3, x0 = 0.0, y0 = 0.0) {
    .Call('_chaoticds_simulate_henon_map_cpp', PACKAGE = 'chaoticds', n, a, b, x0, y0)
}

#' Fast tent map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the tent map.
#'
#' @param n Number of iterations
#' @param r Parameter r
#' @param x0 Initial value
#' @return Numeric vector
#' @export
simulate_tent_map_cpp <- function(n, r, x0) {
    .Call('_chaoticds_simulate_tent_map_cpp', PACKAGE = 'chaoticds', n, r, x0)
}

#' Fast ACF computation (C++ implementation)
#'
#' Efficient computation of autocorrelation function.
#'
#' @param x Numeric vector
#' @param max_lag Maximum lag
#' @return NumericVector of ACF values
#' @export
acf_cpp <- function(x, max_lag) {
    .Call('_chaoticds_acf_cpp', PACKAGE = 'chaoticds', x, max_lag)
}

#' Fast exceedances extraction (C++ implementation)
#'
#' Extract values that exceed threshold.
#'
#' @param x Numeric vector
#' @param threshold Threshold value
#' @return NumericVector of exceedance values
#' @export
exceedances_cpp <- function(x, threshold) {
    .Call('_chaoticds_exceedances_cpp', PACKAGE = 'chaoticds', x, threshold)
}

#' Fast inter-exceedance times (C++ implementation)
#'
#' Compute times between consecutive exceedances.
#'
#' @param exceedance_indices Integer vector of exceedance indices
#' @return IntegerVector of inter-exceedance times
#' @export
inter_exceedance_times_cpp <- function(exceedance_indices) {
    .Call('_chaoticds_inter_exceedance_times_cpp', PACKAGE = 'chaoticds', exceedance_indices)
}

#' Fast empirical CDF (C++ implementation)
#'
#' Compute empirical cumulative distribution function.
#'
#' @param x Numeric vector (data)
#' @param eval_points Numeric vector (points to evaluate CDF)
#' @return NumericVector of CDF values
#' @export
ecdf_cpp <- function(x, eval_points) {
    .Call('_chaoticds_ecdf_cpp', PACKAGE = 'chaoticds', x, eval_points)
}

#' Fast return level estimation (C++ implementation)
#'
#' Estimate return levels from block maxima.
#'
#' @param block_maxima Numeric vector of block maxima
#' @param return_period Integer return period
#' @return Numeric scalar return level estimate
#' @export
return_level_empirical_cpp <- function(block_maxima, return_period) {
    .Call('_chaoticds_return_level_empirical_cpp', PACKAGE = 'chaoticds', block_maxima, return_period)
}

#' Fast bootstrap sample generation (C++ implementation)
#'
#' Generate bootstrap samples efficiently.
#'
#' @param x Numeric vector to resample
#' @param B Number of bootstrap samples
#' @return NumericMatrix with B columns, each a bootstrap sample
#' @export
bootstrap_samples_cpp <- function(x, B) {
    .Call('_chaoticds_bootstrap_samples_cpp', PACKAGE = 'chaoticds', x, B)
}

#' Fast moving average (C++ implementation)
#'
#' Compute moving average for time series.
#'
#' @param x Numeric vector
#' @param window_size Integer window size
#' @return NumericVector of moving averages
#' @export
moving_average_cpp <- function(x, window_size) {
    .Call('_chaoticds_moving_average_cpp', PACKAGE = 'chaoticds', x, window_size)
}

#' Fast threshold stability diagnostic (C++ implementation)
#'
#' Compute mean excess over threshold for threshold selection.
#'
#' @param x Numeric vector
#' @param thresholds Numeric vector of candidate thresholds
#' @return NumericVector of mean excess values
#' @export
mean_excess_cpp <- function(x, thresholds) {
    .Call('_chaoticds_mean_excess_cpp', PACKAGE = 'chaoticds', x, thresholds)
}

#' Fast extremal index intervals estimator (C++ implementation)
#'
#' Ferro-Segers intervals estimator for extremal index.
#'
#' @param x Numeric vector
#' @param threshold Numeric threshold
#' @return Numeric extremal index estimate
#' @export
extremal_index_intervals_cpp <- function(x, threshold) {
    .Call('_chaoticds_extremal_index_intervals_cpp', PACKAGE = 'chaoticds', x, threshold)
}

#' Fast logistic bifurcation diagram data (C++ implementation)
#'
#' Generate bifurcation diagram data efficiently.
#'
#' @param r_values Numeric vector of r parameters
#' @param n_iter Number of iterations per r value
#' @param discard Number of initial iterations to discard
#' @param x0 Initial value
#' @return DataFrame with r and x columns
#' @export
logistic_bifurcation_cpp <- function(r_values, n_iter = 200L, discard = 100L, x0 = 0.2) {
    .Call('_chaoticds_logistic_bifurcation_cpp', PACKAGE = 'chaoticds', r_values, n_iter, discard, x0)
}

#' Fast logistic map simulation (C++ implementation)
#' 
#' Efficient C++ implementation of the logistic map for improved performance
#' with large datasets.
#' 
#' @param n Number of iterations
#' @param r Parameter r of the logistic map
#' @param x0 Initial value
#' @return Numeric vector of the time series
#' @export
simulate_logistic_map_cpp <- function(n, r, x0) {
    .Call('_chaoticds_simulate_logistic_map_cpp', PACKAGE = 'chaoticds', n, r, x0)
}

#' Fast threshold exceedance detection (C++ implementation)
#' 
#' Efficient C++ implementation for finding threshold exceedances.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @return IntegerVector of indices where x > threshold
#' @export
threshold_exceedances_cpp <- function(x, threshold) {
    .Call('_chaoticds_threshold_exceedances_cpp', PACKAGE = 'chaoticds', x, threshold)
}

#' Fast cluster size computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing cluster sizes of exceedances.
#' 
#' @param exceedance_indices Integer vector of exceedance indices
#' @param run_length Maximum gap between exceedances in same cluster
#' @return IntegerVector of cluster sizes
#' @export
cluster_sizes_cpp <- function(exceedance_indices, run_length) {
    .Call('_chaoticds_cluster_sizes_cpp', PACKAGE = 'chaoticds', exceedance_indices, run_length)
}

#' Fast extremal index estimation using runs method (C++ implementation)
#' 
#' Efficient C++ implementation of the runs estimator for extremal index.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @param run_length Run length parameter
#' @return Numeric scalar of extremal index estimate
#' @export
extremal_index_runs_cpp <- function(x, threshold, run_length) {
    .Call('_chaoticds_extremal_index_runs_cpp', PACKAGE = 'chaoticds', x, threshold, run_length)
}

#' Fast block maxima computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing block maxima.
#' 
#' @param x Numeric vector of data
#' @param block_size Size of each block
#' @return NumericVector of block maxima
#' @export
block_maxima_cpp <- function(x, block_size) {
    .Call('_chaoticds_block_maxima_cpp', PACKAGE = 'chaoticds', x, block_size)
}

#' Fast quantile computation (C++ implementation)
#' 
#' Simple quantile computation for threshold selection.
#' 
#' @param x Numeric vector of data
#' @param prob Probability (0 to 1)
#' @return Numeric scalar quantile value
#' @export
quantile_cpp <- function(x, prob) {
    .Call('_chaoticds_quantile_cpp', PACKAGE = 'chaoticds', x, prob)
}

