# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Hénon map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the Hénon map for improved performance.
#'
#' @param n Number of iterations
#' @param a Parameter a
#' @param b Parameter b
#' @param x0 Initial x value
#' @param y0 Initial y value
#' @param noise_sd Additive Gaussian noise SD per iteration (default 0)
#' @return DataFrame with x and y columns
#' @export
simulate_henon_map_cpp <- function(n, a = 1.4, b = 0.3, x0 = 0.0, y0 = 0.0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_henon_map_cpp`, n, a, b, x0, y0, noise_sd)
}

#' Fast tent map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the tent map.
#'
#' @param n Number of iterations
#' @param r Parameter r
#' @param x0 Initial value
#' @param noise_sd Additive Gaussian noise SD per iteration (default 0)
#' @return Numeric vector
#' @export
simulate_tent_map_cpp <- function(n, r, x0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_tent_map_cpp`, n, r, x0, noise_sd)
}

#' Fast ACF computation (C++ implementation)
#'
#' Efficient computation of autocorrelation function.
#'
#' @param x Numeric vector
#' @param max_lag Maximum lag
#' @return NumericVector of ACF values
#' @export
acf_cpp <- function(x, max_lag) {
    .Call(`_chaoticds_acf_cpp`, x, max_lag)
}

#' Fast exceedances extraction (C++ implementation)
#'
#' Extract values that exceed threshold.
#'
#' @param x Numeric vector
#' @param threshold Threshold value
#' @return NumericVector of exceedance values
#' @export
exceedances_cpp <- function(x, threshold) {
    .Call(`_chaoticds_exceedances_cpp`, x, threshold)
}

#' Fast inter-exceedance times (C++ implementation)
#'
#' Compute times between consecutive exceedances.
#'
#' @param exceedance_indices Integer vector of exceedance indices
#' @return IntegerVector of inter-exceedance times
#' @export
inter_exceedance_times_cpp <- function(exceedance_indices) {
    .Call(`_chaoticds_inter_exceedance_times_cpp`, exceedance_indices)
}

#' Fast empirical CDF (C++ implementation)
#'
#' Compute empirical cumulative distribution function.
#'
#' @param x Numeric vector (data)
#' @param eval_points Numeric vector (points to evaluate CDF)
#' @return NumericVector of CDF values
#' @export
ecdf_cpp <- function(x, eval_points) {
    .Call(`_chaoticds_ecdf_cpp`, x, eval_points)
}

#' Fast return level estimation (C++ implementation)
#'
#' Estimate return levels from block maxima.
#'
#' @param block_maxima Numeric vector of block maxima
#' @param return_period Integer return period
#' @return Numeric scalar return level estimate
#' @export
return_level_empirical_cpp <- function(block_maxima, return_period) {
    .Call(`_chaoticds_return_level_empirical_cpp`, block_maxima, return_period)
}

#' Fast bootstrap sample generation (C++ implementation)
#'
#' Generate bootstrap samples efficiently.
#'
#' @param x Numeric vector to resample
#' @param B Number of bootstrap samples
#' @return NumericMatrix with B columns, each a bootstrap sample
#' @export
bootstrap_samples_cpp <- function(x, B) {
    .Call(`_chaoticds_bootstrap_samples_cpp`, x, B)
}

#' Fast moving average (C++ implementation)
#'
#' Compute moving average for time series.
#'
#' @param x Numeric vector
#' @param window_size Integer window size
#' @return NumericVector of moving averages
#' @export
moving_average_cpp <- function(x, window_size) {
    .Call(`_chaoticds_moving_average_cpp`, x, window_size)
}

#' Fast threshold stability diagnostic (C++ implementation)
#'
#' Compute mean excess over threshold for threshold selection.
#'
#' @param x Numeric vector
#' @param thresholds Numeric vector of candidate thresholds
#' @return NumericVector of mean excess values
#' @export
mean_excess_cpp <- function(x, thresholds) {
    .Call(`_chaoticds_mean_excess_cpp`, x, thresholds)
}

#' Fast extremal index intervals estimator (C++ implementation)
#'
#' Ferro-Segers intervals estimator for extremal index.
#'
#' @param x Numeric vector
#' @param threshold Numeric threshold
#' @return Numeric extremal index estimate
#' @export
extremal_index_intervals_cpp <- function(x, threshold) {
    .Call(`_chaoticds_extremal_index_intervals_cpp`, x, threshold)
}

#' Fast Lozi map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the two-dimensional Lozi map.
#'
#' @param n Number of iterations
#' @param a Parameter a
#' @param b Parameter b
#' @param x0 Initial x value
#' @param y0 Initial y value
#' @return DataFrame with x and y columns
#' @export
simulate_lozi_map_cpp <- function(n, a = 1.7, b = 0.5, x0 = 0.0, y0 = 0.0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_lozi_map_cpp`, n, a, b, x0, y0, noise_sd)
}

#' Fast Chirikov standard map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the area-preserving Chirikov-Taylor
#' map on the torus [0, 2*pi)^2.
#'
#' @param n Number of iterations
#' @param K Kick parameter (default 1.2)
#' @param p0 Initial momentum
#' @param theta0 Initial angle
#' @return DataFrame with columns p and theta
#' @export
simulate_standard_map_cpp <- function(n, K = 1.2, p0 = 1.0, theta0 = 1.0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_standard_map_cpp`, n, K, p0, theta0, noise_sd)
}

#' Fast Ikeda map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the two-dimensional Ikeda map.
#'
#' @param n Number of iterations
#' @param u Dissipation parameter (default 0.9)
#' @param x0 Initial x
#' @param y0 Initial y
#' @return DataFrame with columns x and y
#' @export
simulate_ikeda_map_cpp <- function(n, u = 0.9, x0 = 0.0, y0 = 0.0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_ikeda_map_cpp`, n, u, x0, y0, noise_sd)
}

#' Fast Arnold cat map simulation (C++ implementation)
#'
#' Efficient C++ implementation of the Arnold cat map on the unit torus.
#'
#' @param n Number of iterations
#' @param x0 Initial x value
#' @param y0 Initial y value
#' @return DataFrame with x and y columns
#' @export
simulate_cat_map_cpp <- function(n, x0 = 0.1, y0 = 0.1, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_cat_map_cpp`, n, x0, y0, noise_sd)
}

#' Fast Lorenz system simulation (C++ implementation)
#'
#' RK4 integration of the classical Lorenz system, mirroring [simulate_lorenz()].
#'
#' @param t_max Total integration time after any transient
#' @param dt Integration step size
#' @param x0,y0,z0 Initial conditions
#' @param sigma,rho,beta Lorenz parameters
#' @param transient Integration time discarded from the start of the trajectory
#' @return DataFrame with columns t, x, y, z
#' @export
simulate_lorenz_cpp <- function(t_max = 50.0, dt = 0.01, x0 = 1.0, y0 = 1.0, z0 = 1.05, sigma = 10.0, rho = 28.0, beta = 8.0 / 3.0, transient = 0.0) {
    .Call(`_chaoticds_simulate_lorenz_cpp`, t_max, dt, x0, y0, z0, sigma, rho, beta, transient)
}

#' Fast Rossler system simulation (C++ implementation)
#'
#' RK4 integration of the Rossler system, mirroring [simulate_rossler()].
#'
#' @param t_max Total integration time after any transient
#' @param dt Integration step size
#' @param x0,y0,z0 Initial conditions
#' @param a,b,c Rossler parameters
#' @param transient Integration time discarded from the start of the trajectory
#' @return DataFrame with columns t, x, y, z
#' @export
simulate_rossler_cpp <- function(t_max = 200.0, dt = 0.05, x0 = 0.0, y0 = 1.0, z0 = 0.0, a = 0.2, b = 0.2, c = 5.7, transient = 0.0) {
    .Call(`_chaoticds_simulate_rossler_cpp`, t_max, dt, x0, y0, z0, a, b, c, transient)
}

#' Fast forced Duffing oscillator simulation (C++ implementation)
#'
#' RK4 integration of the forced Duffing oscillator, mirroring
#' [simulate_duffing()]. Unlike Lorenz and Rossler the forcing introduces
#' explicit time dependence, so the integrator threads the internal clock
#' through the derivative evaluation.
#'
#' @param t_max Total integration time after any transient
#' @param dt Integration step size
#' @param x0,v0 Initial position and velocity
#' @param alpha,beta,delta,gamma,omega Duffing parameters
#' @param transient Integration time discarded from the start of the trajectory
#' @return DataFrame with columns t, x, v
#' @export
simulate_duffing_cpp <- function(t_max = 100.0, dt = 0.05, x0 = 1.0, v0 = 0.0, alpha = -1.0, beta = 1.0, delta = 0.2, gamma = 0.3, omega = 1.0, transient = 0.0) {
    .Call(`_chaoticds_simulate_duffing_cpp`, t_max, dt, x0, v0, alpha, beta, delta, gamma, omega, transient)
}

#' Fast logistic bifurcation diagram data (C++ implementation)
#'
#' Generate bifurcation diagram data efficiently.
#'
#' @param r_values Numeric vector of r parameters
#' @param n_iter Number of iterations per r value
#' @param discard Number of initial iterations to discard
#' @param x0 Initial value
#' @return DataFrame with r and x columns
#' @export
logistic_bifurcation_cpp <- function(r_values, n_iter = 200L, discard = 100L, x0 = 0.2) {
    .Call(`_chaoticds_logistic_bifurcation_cpp`, r_values, n_iter, discard, x0)
}

#' Fast logistic map simulation (C++ implementation)
#' 
#' Efficient C++ implementation of the logistic map for improved performance
#' with large datasets.
#' 
#' @param n Number of iterations
#' @param r Parameter r of the logistic map
#' @param x0 Initial value
#' @param noise_sd Additive Gaussian noise SD per iteration (default 0)
#' @return Numeric vector of the time series
#' @export
simulate_logistic_map_cpp <- function(n, r, x0, noise_sd = 0.0) {
    .Call(`_chaoticds_simulate_logistic_map_cpp`, n, r, x0, noise_sd)
}

#' Fast threshold exceedance detection (C++ implementation)
#' 
#' Efficient C++ implementation for finding threshold exceedances.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @return IntegerVector of indices where x > threshold
#' @export
threshold_exceedances_cpp <- function(x, threshold) {
    .Call(`_chaoticds_threshold_exceedances_cpp`, x, threshold)
}

#' Fast cluster size computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing cluster sizes of exceedances.
#' 
#' @param exceedance_indices Integer vector of exceedance indices
#' @param run_length Maximum gap between exceedances in same cluster
#' @return IntegerVector of cluster sizes
#' @export
cluster_sizes_cpp <- function(exceedance_indices, run_length) {
    .Call(`_chaoticds_cluster_sizes_cpp`, exceedance_indices, run_length)
}

#' Fast extremal index estimation using runs method (C++ implementation)
#' 
#' Efficient C++ implementation of the runs estimator for extremal index.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @param run_length Run length parameter
#' @return Numeric scalar of extremal index estimate
#' @export
extremal_index_runs_cpp <- function(x, threshold, run_length) {
    .Call(`_chaoticds_extremal_index_runs_cpp`, x, threshold, run_length)
}

#' Fast block maxima computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing block maxima.
#' 
#' @param x Numeric vector of data
#' @param block_size Size of each block
#' @return NumericVector of block maxima
#' @export
block_maxima_cpp <- function(x, block_size) {
    .Call(`_chaoticds_block_maxima_cpp`, x, block_size)
}

#' Fast quantile computation (C++ implementation)
#' 
#' Simple quantile computation for threshold selection.
#' 
#' @param x Numeric vector of data
#' @param prob Probability (0 to 1)
#' @return Numeric scalar quantile value
#' @export
quantile_cpp <- function(x, prob) {
    .Call(`_chaoticds_quantile_cpp`, x, prob)
}

