# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast logistic map simulation (C++ implementation)
#' 
#' Efficient C++ implementation of the logistic map for improved performance
#' with large datasets.
#' 
#' @param n Number of iterations
#' @param r Parameter r of the logistic map
#' @param x0 Initial value
#' @return Numeric vector of the time series
#' @export
simulate_logistic_map_cpp <- function(n, r, x0) {
    .Call(`_chaoticds_simulate_logistic_map_cpp`, n, r, x0)
}

#' Fast threshold exceedance detection (C++ implementation)
#' 
#' Efficient C++ implementation for finding threshold exceedances.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @return IntegerVector of indices where x > threshold
#' @export
threshold_exceedances_cpp <- function(x, threshold) {
    .Call(`_chaoticds_threshold_exceedances_cpp`, x, threshold)
}

#' Fast cluster size computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing cluster sizes of exceedances.
#' 
#' @param exceedance_indices Integer vector of exceedance indices
#' @param run_length Maximum gap between exceedances in same cluster
#' @return IntegerVector of cluster sizes
#' @export
cluster_sizes_cpp <- function(exceedance_indices, run_length) {
    .Call(`_chaoticds_cluster_sizes_cpp`, exceedance_indices, run_length)
}

#' Fast extremal index estimation using runs method (C++ implementation)
#' 
#' Efficient C++ implementation of the runs estimator for extremal index.
#' 
#' @param x Numeric vector of data
#' @param threshold Threshold value
#' @param run_length Run length parameter
#' @return Numeric scalar of extremal index estimate
#' @export
extremal_index_runs_cpp <- function(x, threshold, run_length) {
    .Call(`_chaoticds_extremal_index_runs_cpp`, x, threshold, run_length)
}

#' Fast block maxima computation (C++ implementation)
#' 
#' Efficient C++ implementation for computing block maxima.
#' 
#' @param x Numeric vector of data
#' @param block_size Size of each block
#' @return NumericVector of block maxima
#' @export
block_maxima_cpp <- function(x, block_size) {
    .Call(`_chaoticds_block_maxima_cpp`, x, block_size)
}

#' Fast quantile computation (C++ implementation)
#' 
#' Simple quantile computation for threshold selection.
#' 
#' @param x Numeric vector of data
#' @param prob Probability (0 to 1)
#' @return Numeric scalar quantile value
#' @export
quantile_cpp <- function(x, prob) {
    .Call(`_chaoticds_quantile_cpp`, x, prob)
}

